[package]
name = "net"
version = "0.1.0"
authors = ["loovjo <jonathan.loov@gmail.com>"]

[dependencies]
rocket = "0.3.5"
rocket_codegen = "0.3.5"

zip = "0.2"
reqwest = "0.8"
chrono = "0.4"
select = "0.4"
statrs = "0.9"
rand = "0.4"
rayon = "0.9.0"

serde = "1.0.0"
serde_derive = "1.0.0"
serde_json = "1.0.0"

lazy_static = "1.0"