[package]
name = "net"
version = "0.1.0"
authors = ["loovjo <jonathan.loov@gmail.com>"]

[dependencies]
rocket = "0.3.10"
rocket_codegen = "0.3.10"

zip = "0.3.2"
reqwest = "0.8.5"
chrono = "0.4.2"
select = "0.4.2"
statrs = "0.9.0"
rand = "0.4.2"
rayon = "1.0.1"

serde = "1.0.55"
serde_derive = "1.0.55"
serde_json = "1.0.17"

lazy_static = "1.0.0"
